[OnlineSubsystemMcp.Xmpp]
bUseSSL=false
ServerAddr="ws://26.242.84.178"
ServerPort=443

[OnlineSubsystemMcp.Xmpp Prod]
bUseSSL=false
ServerAddr="ws://26.242.84.178"
ServerPort=443

[OnlineSubsystemMcp]
bUsePartySystemV2=true

[OnlineSubsystemMcp.OnlinePartySystemMcpAdapter]
bUsePartySystemV2=true

[CrashContextProperties]
CrashReportClientRichText=NSLOCTEXT("FortGlobals", "FortniteCrashReportClientText", "Fortnite has crashed! GGs")

[/Script/Qos.QosRegionManager]
NumTestsPerRegion=1
PingTimeout=3.0
!RegionDefinitions=ClearArray
+RegionDefinitions=(DisplayName="North America", RegionId="NAE", bEnabled=true, bVisible=true, bAutoAssignable=true)
+RegionDefinitions=(DisplayName="Europe", RegionId="EU", bEnabled=false, bVisible=true, bAutoAssignable=false)

[XMPP]
bEnableWebsockets=true

[/Script/Qos.QosRegionManager]
NumTestsPerRegion=1
PingTimeout=3.0

# Double Pump
;[ConsoleVariables]
;Weapon.TryToFireRestrictedByTypeCooldowns=0